@host=http://api-diad.test

### Get total de preinscritos por fecha
GET {{host}}/api/admission/applicants-preregister-count

### Get total de pagos por fecha
GET {{host}}/api/admission/payments-count

# Simulacro
### Get total de inscritos al simulacro
GET {{host}}/api/simulation/applicants-simulation-count

### Get total de pagos al simulacro
GET {{host}}/api/simulation/payments-simulation-count

### Get Semibecas
GET {{host}}/api/admission/partial-scholarship-count

### Get postulantes de cepre de vocacional
GET {{host}}/api/admission/applicants-vocational-cepre-intensive-count

### Get postulantes de cepre de vocacional Intensivo
GET {{host}}/api/admission/applicants-vocational-cepre-count

### Get postulantes de vocacional
GET {{host}}/api/admission/applicants-vocational-count

### Get status de revision de Declaracion Jurada
GET {{host}}/api/admission/sworn-declaration